### ISSUE TITLE
Conflict with the 'microscope' extension

### ISSUE THREAD

**Issue by r-ryabikov** [tackme31/howmessy#5] opened 2023-11-22 14:24 UTC
https://github.com/bert2/microscope/ is an extension to display IL assembly generated by a particular .NET method.
Whenever it is used together with howmessy, whichever extension happens to load later fails to analyse any methods and shows "An error occurred loading this property page" error message on all of its Options pages.
Sister issue on microscope repository:
https://github.com/bert2/microscope/issues/7

**Comment by tackme31** [comment] 2023-11-22 15:18
@r-ryabikov 
Thank you for reporting. Since howmessy partially references code from the microscope, it is highly likely that this repository is the cause of the issue. I will address this issue in this repository, so please close the issue on the microscope side.

**Comment by bert2** [comment] 2023-11-22 16:58
I only had a quick look but the problem might by the class name of the options. We both named them `GeneralOptions` and the `BaseOptionModel` uses the [type name as a key](https://github.com/bert2/microscope/blob/main/src/VSExtension/Options/BaseOptionModel.cs#L82) to store the options in the registry. Renaming the class or overriding the `CollectionName` property in `GeneralOptions` could help.

**Comment by tackme31** [comment] 2023-11-22 17:45
The issue occurred due to a duplicate [PackageId](https://github.com/tackme31/howmessy/blob/fd74efac86ed576c7e5d8776e9a86a8af88454fe/Howmessy.VSExtension/HowmessyCommands.vsct#L4) between howmessy and microscope. Presumably, Visual Studio manages options using this ID. By setting a unique PackageId, I have confirmed that the options can be displayed correctly.

I will release the fixed version to the Marketplace at a later date, so please be patient for a while.

**Comment by r-ryabikov** [comment] 2023-11-23 06:31
Thank you both for a quick response and work on your extensions, which I found useful.

**Closed** 2023-11-27 17:07 UTC
